Add set of validations
hivesolutions/yonius pull request #14
Opened 2020-09-16 16:31 UTC by gcandal

2020-09-16 16:31 UTC, gcandal commented
@joamag based on https://github.com/hivesolutions/appier/blob/92f90e40637e9a5c249c4c47bba96741f21c97d4/src/appier/validation.py

2020-09-17 11:13 UTC, joamag requested changes

2020-09-17 11:13 UTC, joamag commented on js/util/validation.js
> +export const isEmail = function(valueC, message = "Value is not a valid email") {
let's remove the `valueC` for the situations where it is not needed

2020-09-17 11:20 UTC, joamag approved these changes

2020-09-17 11:20 UTC, merged