feat: reference support
hivesolutions/yonius pull request #33
Opened 2021-04-20 11:39 UTC by gcandal

2021-04-20 11:43 UTC, gcandal commented
@joamag

2021-04-20 17:29 UTC, joamag commented
@gcandal please change the pending stuff, including the code that is commented out

2021-04-21 17:19 UTC, gcandal commented
@joamag

2021-04-22 16:48 UTC, joamag requested changes

2021-04-22 16:48 UTC, joamag commented on js/data/collection.js
> +    [Reference, Number],
Object ??

2021-04-22 16:48 UTC, joamag commented on test/data/model.js
> +            assert.strictEqual(person.cats.isResolved, false);
@gcandal add type assertions

2021-04-29 14:18 UTC, gcandal commented
@joamag

2021-05-03 15:12 UTC, joamag requested changes

2021-05-03 15:12 UTC, joamag commented on js/data/model.js
> +            // if (Array.isArray(value) && value.length === 0) {
remove comments

2021-05-03 15:14 UTC, joamag approved these changes

2021-05-03 15:14 UTC, merged